#!/bin/bash

# HIGH Priority commands:
sudo apt update
sudo apt upgrade -y
sudo apt install gcc -y
sudo apt install g++ -y
sudo apt install gdb -y
sudo apt install git -y
sudo apt install build-essential -y
sudo apt purge vim -y
sudo hash -d vim
sudo apt install vim-gtk -y
#sudo apt install i3 -y
sudo apt install snapd -y
sudo apt install gh -y
sudo apt install python3-dev python3-pip python3-setuptools -y
sudo apt install pipx -y
sudo apt install pavucontrol -y
sudo apt install tig -y # Git Repository Browser
sudo apt install linux-headers-$(uname -r) -y
sudo apt install tmux -y
sudo apt install util-linux -y
sudo apt install libreadline-dev -y

# INSTALL VS CODE:
# https://wiki.debian.org/VisualStudioCode
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/keyrings/microsoft-archive-keyring.gpg
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt-get update
sudo apt-get install code

# RICE LINUX
pipx install qtile
pipx install pywal
sudo apt install picom -y
sudo apt install brightnessctl -y
sudo apt install playerctl -y
sudo apt install pactl -y

# INVERT THE MOUSE SCROLL WHEEL DIRECTION TO NATURAL:
sudo mkdir -p /etc/X11/xorg.conf.d/ # Per precauzione
sudo bash -c 'cat << EOF > /etc/X11/xorg.conf.d/40-libinput.conf
Section "InputClass"
    Identifier "My Mouse"
    MatchIsPointer "on"
    Option "NaturalScrolling" "true"
EndSection
EOF'

# LOW Priority commands
mkdir ~/.vim
git clone https://github.com/flazz/vim-colorschemes.git ~/.vim
sudo apt install papirus-icon-theme -y
sudo apt-get install imagemagick -y
sudo apt install thunderbird -y
sudo apt-get install thunar -y
sudo apt install lxappearance -y
sudo apt install gtk-chtheme -y
sudo apt install evince -y # PDF reader

echo "Controlla che funzioni vim, altrimenti trova il vim-gtk adatto."
read -p "~~~ DONE! Press enter to exit."
